### ISSUE TITLE
The Link to Full Series (in blog.stephensanwo) is Not Working

### ISSUE THREAD

**Issue by rukshar69** [stephensanwo/fullstack-ai-chatbot#7]
I tried to go to the full series blog using the provided [URL](https://blog.stephensanwo.dev/series/build-ai-chatbot). But in the blog it's showing Page Not Found (as seen in the screenshot)

![image](https://github.com/user-attachments/assets/9cb23681-13fb-494f-bfbe-d29bb7941312)

**Comment by stephensanwo** [comment]
I think its broken somewhere
https://blog.stephensanwo.dev/build-a-fullstack-ai-chatbot/series
